"""R5 (hermetic, DB-backed): deep KG relationship mining — co-delivery association over the Jira
corpus, unified strength/novelty, and the "relationships you may be missing" discovery surface.

carry_forward auto-mines the graph, so provisioning + carrying v7 yields gated ``co_delivered``
``pending_edge``s (market-basket lift/PMI over ``control.story_catalogue_link``) alongside the
structural co-membership kinds. Every proposal is gated G1-G8; the top NOVELTY edges are the
strong-but-non-obvious CROSS-PILLAR co-delivery bonds the flat catalogue hides; each edge's basis
reconciles against the real corpus; and approval promotes it to a ``kg_edge`` that keeps its "why".
Deterministic + zero-spend (the counts are hermetic-identical to live).
"""

from __future__ import annotations

import asyncio
import json
import os
from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import Engine, create_engine, text

from app import db
from app.main import create_app
from app.services import kg as kg_svc
from app.services import provision
from app.services import stories as story_svc

needs_db = pytest.mark.skipif(
    not os.environ.get("DATABASE_URL"), reason="DATABASE_URL not set (DB-backed test)"
)


@pytest.fixture(scope="module")
def provisioned() -> Iterator[None]:
    from app import migrate

    migrate.run()

    async def _setup() -> None:
        db.init_engine()
        await provision.bring_version_online("v7")
        # carry_forward populates story_catalogue_link (the co-delivery basket source); the gated
        # proposals are generated by the admin scan endpoint / weekly KG schedule — here we call the
        # same entrypoint once so co_delivered proposals exist for every test.
        await story_svc.carry_forward("v7")
        await kg_svc.propose_structural_edges("v7")
        await db.dispose_engine()

    async def _teardown() -> None:
        db.init_engine()
        engine = db.get_engine()
        assert engine is not None
        async with engine.begin() as conn:
            await conn.execute(text("DELETE FROM control.kg_edge"))
            await conn.execute(text("DELETE FROM control.pending_edge"))
            await conn.execute(text("DELETE FROM control.change_flag"))
            await conn.execute(text("DELETE FROM control.citation"))
            await conn.execute(text("DELETE FROM control.validation_gate_run"))
            await conn.execute(text("DELETE FROM control.reasoning_step"))
            await conn.execute(text("DELETE FROM control.reasoning_chain"))
            await conn.execute(text("DELETE FROM control.kg_node"))
            await conn.execute(text("DELETE FROM control.evidence_item WHERE kind = 'catalogue'"))
            await conn.execute(
                text("DELETE FROM control.audit_log WHERE action LIKE 'change_flag%'")
            )
            await conn.execute(text("DELETE FROM control.story_use_case_carry"))
            await conn.execute(text("DELETE FROM control.story_subcap_carry"))
            await conn.execute(text("DELETE FROM control.story"))
            await conn.execute(text("DROP SCHEMA IF EXISTS cat_v7 CASCADE"))
            await conn.execute(
                text("DELETE FROM control.catalogue_version WHERE version_id = 'v7'")
            )
        await db.dispose_engine()

    asyncio.run(_setup())
    yield
    asyncio.run(_teardown())


@pytest.fixture
def client(provisioned: None) -> Iterator[TestClient]:
    with TestClient(create_app()) as c:
        yield c


def _sync() -> Engine:
    return create_engine(os.environ["DATABASE_URL"].replace("+asyncpg", "+psycopg"))


@needs_db
def test_co_delivery_mined_and_gated(client: TestClient) -> None:
    """The corpus yields real ``co_delivered`` proposals, and every one PASSED G1-G8 (nothing
    ungated leaks) — a dashed pending_edge + a Change-Flags item, never a live kg_edge."""
    with _sync().connect() as c:
        codel = c.execute(
            text(
                "SELECT count(*) FROM control.pending_edge "
                "WHERE version_id = 'v7' AND kind = 'co_delivered' AND status = 'pending'"
            )
        ).scalar_one()
        flags = c.execute(
            text(
                "SELECT count(*) FROM control.change_flag "
                "WHERE kind = 'kg_edge_proposal' AND detail->>'kind_edge' = 'co_delivered'"
            )
        ).scalar_one()
        passed = c.execute(
            text(
                "SELECT count(*) FROM control.change_flag cf "
                "JOIN control.validation_gate_run g ON g.chain_id = cf.chain_id "
                "WHERE cf.kind = 'kg_edge_proposal' "
                "AND cf.detail->>'kind_edge' = 'co_delivered' AND g.verdict = 'pass'"
            )
        ).scalar_one()
    assert codel > 0, "expected co-delivery proposals mined from the Jira corpus"
    assert flags == codel and passed == flags  # every co_delivered proposal is gated, all passed


@needs_db
def test_co_delivery_detail_envelope_complete(client: TestClient) -> None:
    """Every co_delivered proposal carries the full R5 envelope — strength, novelty, basis, crosses
    — so the graph can weight it, rank it, explain it, and flag its cross-pillar reach."""
    with _sync().connect() as c:
        bad = c.execute(
            text(
                "SELECT count(*) FROM control.pending_edge "
                "WHERE version_id = 'v7' AND kind = 'co_delivered' AND ("
                "  detail IS NULL OR detail->>'basis' IS NULL "
                "  OR (detail->>'novelty') IS NULL OR (detail->>'strength') IS NULL "
                "  OR detail->>'crosses' IS NULL)"
            )
        ).scalar_one()
        weightless = c.execute(
            text(
                "SELECT count(*) FROM control.pending_edge "
                "WHERE version_id = 'v7' AND kind = 'co_delivered' AND weight IS NULL"
            )
        ).scalar_one()
    assert bad == 0 and weightless == 0


@needs_db
def test_co_delivery_reconciles_with_corpus(client: TestClient) -> None:
    """Grounded, not fabricated: a mined co_delivered edge's ``co_stories`` count matches a direct
    same-story co-occurrence count over the real corpus (control.story_catalogue_link)."""
    with _sync().connect() as c:
        row = (
            c.execute(
                text(
                    "SELECT fn.ref_id AS a, tn.ref_id AS b, "
                    "(pe.detail->>'co_stories')::int AS co_stories "
                    "FROM control.pending_edge pe "
                    "JOIN control.kg_node fn ON fn.node_id = pe.from_node "
                    "JOIN control.kg_node tn ON tn.node_id = pe.to_node "
                    "WHERE pe.version_id = 'v7' AND pe.kind = 'co_delivered' "
                    "AND (pe.detail->>'co_stories')::int > 0 "
                    "ORDER BY (pe.detail->>'co_stories')::int DESC LIMIT 1"
                )
            )
            .mappings()
            .first()
        )
        assert row is not None, "expected a same-story co-delivery pair to reconcile"
        actual = c.execute(
            text(
                "SELECT count(DISTINCT l1.story_key) FROM control.story_catalogue_link l1 "
                "JOIN control.story_catalogue_link l2 ON l2.story_key = l1.story_key "
                "WHERE l1.version_id = 'v7' AND l2.version_id = 'v7' "
                "AND l1.subcap_id = :a AND l2.subcap_id = :b"
            ),
            {"a": row["a"], "b": row["b"]},
        ).scalar_one()
    assert actual == row["co_stories"]  # the basis is the real corpus count, not a guess


@needs_db
def test_discover_ranks_cross_pillar_novelty_first(client: TestClient) -> None:
    """The headline: /kg/discover ranks the strong-AND-non-obvious links first. The #1 relationship
    "you may be missing" is a CROSS-PILLAR co-delivery bond (high novelty), and the payload is
    monotonically novelty-descending — obvious same-pillar siblings never lead."""
    disc = client.get("/api/catalogue/v7/kg/discover?limit=20").json()
    latent = disc["latent"]
    assert latent, "discovery surface should not be empty"
    novelties = [e["novelty"] for e in latent]
    assert novelties == sorted(novelties, reverse=True)  # ranked by novelty
    top = latent[0]
    assert top["crosses"] == "cross_pillar"  # strong-but-not-obvious leads
    assert top["novelty"] > 0.5 and top["basis"] and top["pending_id"]


@needs_db
def test_ego_graph_weights_and_explains_edges(client: TestClient) -> None:
    """The per-subcap KG carries weighted, explained edges + a per-subcap latent panel. Pick a
    subcap that centres a co_delivered proposal and assert its dashed edge has strength + basis +
    crosses, and the ego "you may be missing" panel is populated."""
    with _sync().connect() as c:
        sid = c.execute(
            text(
                "SELECT fn.ref_id FROM control.pending_edge pe "
                "JOIN control.kg_node fn ON fn.node_id = pe.from_node "
                "WHERE pe.version_id = 'v7' AND pe.kind = 'co_delivered' LIMIT 1"
            )
        ).scalar_one()
    kg = client.get(f"/api/catalogue/v7/kg?subcap={sid}").json()
    codel = [e for e in kg["pending"] if e["kind"] == "co_delivered"]
    assert codel, "expected a dashed co_delivered edge on this subcap"
    e = codel[0]
    assert e["strength"] and e["basis"] and e["crosses"] and e["layer"] == "B_proposed"
    assert kg["latent"], "ego 'relationships you may be missing' panel should be populated"
    # Layer-A now also projects offering / value-chain siblings, each with its own strength + basis.
    assert any(x["kind"] == "same_value_chain" and x["strength"] for x in kg["edges"]) or any(
        x["kind"] == "shares_offering" and x["strength"] for x in kg["edges"]
    )


@needs_db
def test_approve_promotes_co_delivered_keeping_its_why(client: TestClient) -> None:
    """Approving a co_delivered proposal re-gates and promotes its pending_edge to an accepted
    Layer-B kg_edge that STILL carries its basis (migration 0014 detail) — an accepted edge can
    always explain itself."""
    flags = client.get("/api/change-flags?status=open").json()["flags"]
    f = next(
        x for x in flags if x["kind"] == "kg_edge_proposal" and str(x["target"]).endswith(":cd")
    )
    approved = client.post(f"/api/change-flags/{f['id']}/approve").json()
    assert approved["resolved"] is True and approved["status"] == "approved"
    with _sync().connect() as c:
        edge = (
            c.execute(
                text(
                    "SELECT detail FROM control.kg_edge "
                    "WHERE version_id = 'v7' AND kind = 'co_delivered' "
                    "ORDER BY edge_id DESC LIMIT 1"
                )
            )
            .mappings()
            .first()
        )
    assert edge is not None
    detail = edge["detail"] if isinstance(edge["detail"], dict) else json.loads(edge["detail"])
    assert detail and detail.get("basis") and detail.get("kind_edge") == "co_delivered"


@needs_db
def test_mining_idempotent_and_bounded(client: TestClient) -> None:
    """Re-mining proposes nothing new (pair-level idempotency), and the whole run stays under the
    per-scan proposal cap (resilience: bounded everything)."""
    from app.intelligence import gates

    again = client.post("/api/admin/kg/propose/v7").json()
    assert again["created"] == 0 and again["already"] > 0
    with _sync().connect() as c:
        total = c.execute(
            text("SELECT count(*) FROM control.pending_edge WHERE version_id = 'v7'")
        ).scalar_one()
    assert total <= gates.knowledge_graph_full_config().max_proposals
