#!/usr/bin/env python3
"""Regenerate the enrichment seed's platform + use-case tables from the base catalogue.

WHY: the base catalogue (``seed/catalogue_v7.json.gz``) carries platforms + use-cases for ALL 851
subcaps, but the separate enrichment seed (``seed/catalogue_v7_enrichment.json.gz``, the normalised
relational tables that provisioning loads into ``cat_<v>``) was generated by an upstream pass that
UNDER-PARSED them — only 415/851 subcaps had a platform and 400/851 a use-case, so half the deep
dives showed "0 linked L3s / use cases". (personas + maturity were already complete; this script
leaves them, and every other seed field, untouched.)

The L3 cell packs multiple platforms in one ``name`` — ``Salesforce Flow (count: 5)\\n[L3-SF-OMNI]
OmniStudio (count: 5)`` — so the first L3 is the entry's ``id`` and the rest are ``[L3-id] Name``
markers in the name. We unpack every L3, strip the ``(count: N)`` suffix, and emit one
``subcap_platform`` row per (subcap, L3). Use-cases come from each subcap's ``uc`` list
(``{uc, arch, text}``). Any L3 referenced but missing from the existing rich ``l3_platforms`` list is
added with its name + a vendor inferred from the ``L3-<VENDOR>-`` id prefix (FK-safe).

Idempotent + reproducible from in-repo data. Usage: ``python3 scripts/regen_enrichment_from_catalogue.py``
"""

from __future__ import annotations

import gzip
import json
import re
from pathlib import Path

SEED_DIR = Path(__file__).resolve().parent.parent / "backend" / "seed"
ENRICH = SEED_DIR / "catalogue_v7_enrichment.json.gz"
BASE = SEED_DIR / "catalogue_v7.json.gz"
_COUNT = re.compile(r"\s*\(count:\s*\d+\)\s*$")
_MARKER = re.compile(r"\[(L3-[A-Z0-9-]+)\]\s*([^\n\[]*)")
_PREFIX = re.compile(r"(L3-[A-Z0-9]+)-")


def _parse_l3s(platforms: list[dict]) -> dict[str, str]:
    """Every (l3_id -> name) packed into a subcap's platform cells."""
    out: dict[str, str] = {}
    for p in platforms:
        name = p.get("name", "") or ""
        first = p.get("id")
        if first:
            lead = re.split(r"\s*\n?\s*\[L3-", name)[0]
            out[first] = _COUNT.sub("", lead).strip() or first
        for l3id, l3name in _MARKER.findall(name):
            out[l3id] = _COUNT.sub("", l3name).strip() or out.get(l3id) or l3id
    return out


def main() -> None:
    seed = json.loads(gzip.open(ENRICH, "rt").read())
    base = json.loads(gzip.open(BASE, "rt").read())["subcaps"]
    l3_meta = {lp["l3_id"]: lp for lp in seed["l3_platforms"]}
    prefix_vendor: dict[str, str] = {}
    for lp in seed["l3_platforms"]:
        m = _PREFIX.match(lp["l3_id"])
        if m and lp.get("vendor_id"):
            prefix_vendor.setdefault(m.group(1), lp["vendor_id"])

    subcap_platforms: list[dict] = []
    use_cases: list[dict] = []
    seen_l3: dict[str, str] = {}
    for x in base:
        sid = x["id"]
        for l3id, l3name in _parse_l3s(x.get("platforms") or []).items():
            subcap_platforms.append({"subcap_id": sid, "l3_id": l3id})
            seen_l3.setdefault(l3id, l3name)
        for u in x.get("uc") or []:
            ucid = u.get("uc") or f"UC{len(use_cases)}"
            arch = u.get("arch") or u.get("archetype") or "GENERAL"
            use_cases.append(
                {
                    "use_case_id": f"{sid}.{ucid}",
                    "subcap_id": sid,
                    "archetype": arch,
                    "name": arch,
                    "description": u.get("text") or u.get("desc") or "",
                }
            )

    l3_platforms = list(seed["l3_platforms"])
    for l3id, l3name in seen_l3.items():
        if l3id in l3_meta:
            continue
        m = _PREFIX.match(l3id)
        l3_platforms.append(
            {
                "l3_id": l3id,
                "vendor_id": prefix_vendor.get(m.group(1)) if m else None,
                "name": l3name,
                "category": "Platform",
                "description": None,
                "reference_url": None,
            }
        )

    l3_ids = {lp["l3_id"] for lp in l3_platforms}
    assert all(
        sp["l3_id"] in l3_ids for sp in subcap_platforms
    ), "dangling L3 reference"

    seed["subcap_platforms"] = subcap_platforms
    seed["use_cases"] = use_cases
    seed["l3_platforms"] = l3_platforms
    with gzip.open(ENRICH, "wt") as f:
        json.dump(seed, f)

    n = len(base)
    print(
        f"subcap_platforms: {len(subcap_platforms)} over {len({s['subcap_id'] for s in subcap_platforms})}/{n} subcaps"
    )
    print(
        f"use_cases: {len(use_cases)} over {len({s['subcap_id'] for s in use_cases})}/{n} subcaps"
    )
    print(
        f"l3_platforms: {len(l3_platforms)} (+{len(l3_platforms) - len(l3_meta)} new)"
    )


if __name__ == "__main__":
    main()
